# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "dm_hana_adapter"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["NA"]
  s.date = "2013-09-04"
  s.description = "A DataMapper DataObjects implementation that uses ODBC to work against SAP's HANA in-memory database offering."
  s.email = "support@anypresence.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "dm_hana_adapter.gemspec",
    "lib/dm_hana_adapter.rb",
    "lib/dm_hana_adapter/dm_do_hana_adapter.rb",
    "lib/dm_hana_adapter/dm_do_hana_migrations.rb",
    "lib/dm_hana_adapter/do_hana_command.rb",
    "lib/dm_hana_adapter/do_hana_connection.rb",
    "lib/dm_hana_adapter/do_hana_quoting.rb",
    "lib/dm_hana_adapter/do_hana_reader.rb",
    "spec/do-hana-adapter_spec.rb",
    "spec/odbc.ini",
    "spec/odbcinst.ini",
    "spec/spec_helper.rb",
    "vendor/ruby-odbc-0.99994/COPYING",
    "vendor/ruby-odbc-0.99994/ChangeLog",
    "vendor/ruby-odbc-0.99994/GPL",
    "vendor/ruby-odbc-0.99994/MANIFEST",
    "vendor/ruby-odbc-0.99994/README",
    "vendor/ruby-odbc-0.99994/ext/extconf.rb",
    "vendor/ruby-odbc-0.99994/ext/init.c",
    "vendor/ruby-odbc-0.99994/ext/odbc.c",
    "vendor/ruby-odbc-0.99994/ext/utf8/extconf.rb",
    "vendor/ruby-odbc-0.99994/ext/utf8/init.c",
    "vendor/ruby-odbc-0.99994/ext/utf8/odbc.c",
    "vendor/ruby-odbc-0.99994/lib/cqgen.rb",
    "vendor/ruby-odbc-0.99994/test/00connect.rb",
    "vendor/ruby-odbc-0.99994/test/10create_table.rb",
    "vendor/ruby-odbc-0.99994/test/20insert.rb",
    "vendor/ruby-odbc-0.99994/test/30select.rb",
    "vendor/ruby-odbc-0.99994/test/40update.rb",
    "vendor/ruby-odbc-0.99994/test/50drop_table.rb",
    "vendor/ruby-odbc-0.99994/test/70close.rb",
    "vendor/ruby-odbc-0.99994/test/test.rb",
    "vendor/ruby-odbc-0.99994/test/utf8/test.rb"
  ]
  s.homepage = "http://github.com/AnyPresence/do-hana-adapter"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.3"
  s.summary = "SAP HANA DataMapper DataObjects Adapter"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<dm-core>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<dm-types>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<dm-migrations>, ["~> 1.2.0"])
      s.add_runtime_dependency(%q<data_objects>, ["~> 0.10.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<ruby-odbc>, ["~> 0.99995"])
    else
      s.add_dependency(%q<dm-core>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-types>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
      s.add_dependency(%q<dm-migrations>, ["~> 1.2.0"])
      s.add_dependency(%q<data_objects>, ["~> 0.10.7"])
      s.add_dependency(%q<rspec>, ["~> 2.10.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<ruby-odbc>, ["~> 0.99995"])
    end
  else
    s.add_dependency(%q<dm-core>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-types>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-do-adapter>, ["~> 1.2.0"])
    s.add_dependency(%q<dm-migrations>, ["~> 1.2.0"])
    s.add_dependency(%q<data_objects>, ["~> 0.10.7"])
    s.add_dependency(%q<rspec>, ["~> 2.10.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<ruby-odbc>, ["~> 0.99995"])
  end
end

